### ISSUE TITLE
路径有问题，无法正常编译

### ISSUE THREAD

**Issue by BackTrackCRoot** [1694439208/gumbo-Elss#1]
能否发布的时候修改一下项目的路径为相对路径，代码是绝对路径得修改好了才能编译的。
![1](https://user-images.githubusercontent.com/4964761/59561940-72db3080-9058-11e9-9a32-271386afc57c.png)

**Comment by BackTrackCRoot** [comment]
并且缺少tag.c等多个文件

**Comment by 1694439208** [comment]
基于gumbo开源库，代码量也没多少，所以就比较乱

**Comment by BackTrackCRoot** [comment]
Thanks
